### ISSUE TITLE
Models Specification

### ISSUE THREAD

**Issue by arstropica** [marmg/NER-Demo#1]
Please can you let me know which language models are required?  The README link references a repository search with many different options.
Thank you.

**Comment by marmg** [comment]
Hello. This is an old project and I'm afraid the models I used are no longer available in the Huggingface hub. The models I used were based on Albert, so any Albert model could be used. For NER I used one trained over Conll-03 and for QA I used one trained over SQuAD.

**Comment by ghost** [comment]
Can you please specify some alternative Albert Model used for NER in Huggingface Hub and also for QA.
